version: "3.7"

services:
  frontend:
    build: ./portfolio-v2
    volumes:
    - ./portfolio-v2:/frontend
    - node_modules:/frontend/node_modules
    ports: 
      - "3000:3000"
      - "24678:24678"
volumes:
  node_modules: